#!/bin/bash
set -e

systemctl daemon-reload
systemctl enable lanternd.service
systemctl start lanternd.service

update-desktop-database /usr/share/applications/ 2>/dev/null || true
gtk-update-icon-cache /usr/share/icons/hicolor/ 2>/dev/null || true
